### ISSUE TITLE
Unable to Upload Code

### ISSUE THREAD

**Issue by Mayank-16** [gutierrezps/proteus-lib#1]
Unable to dump code in D1-Mini Wemos. Theres no way I can find a place to upload a hex file.

**Comment by gutierrezps** [comment]
It is not an active component i.e. you can't simulate it, sorry.

**Comment by Mayank-16** [comment]
Is there any way to get Active component? If you know some libraries can
you please share with me. 'Cause I am unable to find on internet.

**Comment by gutierrezps** [comment]
I'm not aware of any ESP8266 active library. AVR simulations on Proteus already are slow for non-trivial code, I don't think it could simulate an ESP8266.
